services:
  frontend:
    build:
      context: .
      dockerfile: ./frontend/Dockerfile
    ports:
      - "3000:3000"
    volumes:
      - ./shared:/shared
      - ./frontend:/app
      - /app/node_modules
    environment:
      - NODE_ENV=production
    env_file: "./frontend/.env"
    depends_on:
      - backend
    working_dir: /app

  backend:
    build:
      context: .
      dockerfile: ./backend/Dockerfile
    ports:
      - "8000:8000"
    volumes:
      - ./shared:/shared
      - ./backend:/app
      - /app/node_modules
    environment:
      - NODE_ENV=production
    working_dir: /app
